name: Feature Request
description: Suggest a new feature or enhancement for OpenReel
title: "[Feature]: "
labels: ["needs-claude-review", "type-feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Claude AI will review this request and discuss the implementation approach.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when I have to manually adjust 100 clips one by one...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        Add a "Batch Edit" feature that lets you:
        1. Select multiple clips
        2. Apply changes to all at once
        3. Preview before applying
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: I tried using adjustment layers but that doesn't work for my use case...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Must-have (Blocking my workflow)
        - Nice-to-have (Would improve workflow)
        - Low (Small improvement)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is?
      options:
        - Simple (Small UI change or tweak)
        - Medium (New component or moderate logic)
        - Complex (Significant architecture change)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other Tools
      description: Does any other tool have this feature? How do they implement it?
      placeholder: |
        DaVinci Resolve has this feature:
        - You select clips and click "Batch Edit"
        - A dialog shows all editable properties
        - Changes apply to all selected clips

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Sketches
      description: Add any visual mockups or UI sketches
      placeholder: Drag and drop images here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: This feature aligns with OpenReel's goal of browser-based video editing
          required: true
        - label: I am willing to help test this feature once implemented
          required: false
